### ISSUE TITLE
Documentation - Project Class Diagram

### ISSUE THREAD

**Issue by mondial7** [kaca1707/supplychain#3]
Hola! Would it be possible to have the final class diagram of the project here on the repo? or as an attachment to this issue?

We might then append here, other partial class diagrams we are using for teams communication.

**Comment by kaca1707** [comment]
Here you go, I think it is better to be here :)
![IMG_4162](https://user-images.githubusercontent.com/35567260/54878325-48981f00-4e2b-11e9-93a0-1e8b0549fa83.JPG)
![InkedFinalClassD_LI](https://user-images.githubusercontent.com/35567260/54878329-564da480-4e2b-11e9-8844-3cc9a6a4539c.jpg)
