### ISSUE TITLE
Typo on method name: "saveBlockhain" -> "saveBlockchain"

### ISSUE THREAD

**Issue by mondial7** [kaca1707/supplychain#8]
https://github.com/kaca1707/supplychain/blob/87b7741e95ceb79a07ede485d1039cc457b5e3f0/src/main/java/upm/softwaredesign/finalproject/service/BlockchainService.java#L28

**Comment by kaca1707** [comment]
Also type should be changed to boolean

**Comment by washington1983** [comment]
I has been applied, to return the same blokchain from database
